# Generated by Django 4.2.2 on 2023-06-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='image',
        ),
    ]
